# Author: Jet Anderson <jet@sourceclear.com>
# github: https://github.com/srcclr/agent-docker-example
# USAGE: Rename 'Dockerfile.example' to 'Dockerfile' before using

FROM      ubuntu:latest

RUN       echo "please edit the Dockerfile with token and app before you use this" ; exit 1

RUN       apt-get -y update && \
          apt-get install -y curl python-pip && \
          mkdir -p /home/app

ADD      vulnerable_app  /home/app/

WORKDIR   /home/app

RUN       pip install --no-cache-dir -r /home/app/requirements.txt

ENV       SRCCLR_API_TOKEN=paste_token_here

RUN       curl -sSL https://download.sourceclear.com/ci.sh | CACHE_DIR=/tmp SCAN_DIR=/home/app bash
